### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ScriptJunkieMC** [Kubajsa/randomTp#40]
**Version of the plugin**
To see the version of the plugin do the command "/rtplugin"
2.19.3

**Describe the bug**
- When i do RTP on my server it does not use the borders set in the config for 1. and for 2 it throws the below error and 3. crashes my server after 2nd / 3rd rtp.

[17:12:02 ERROR]: Invalid bounding box data, inverted bounds for: StructureBoundingBox{minX=2147483647, minY=2147483647, minZ=2147483647, maxX=-2147483648, maxY=-2147483648, maxZ=-2147483648}
[17:12:02 ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid call to EmtyPoolElement.getBoundingBox, filter me!
        at net.minecraft.world.level.levelgen.feature.structures.WorldGenFeatureDefinedStructurePoolEmpty.a(WorldGenFeatureDefinedStructurePoolEmpty.java:39) ~[patched_1.17.1.jar:git-Paper-188]
        at net.minecraft.world.level.levelgen.structure.WorldGenFeaturePillagerOutpostPoolPiece.<init>(WorldGenFeaturePillagerOutpostPoolPiece.java:57) ~[patched_1.17.1.jar:git-Paper-188]
        at net.minecraft.world.level.levelgen.feature.StructureGenerator.a(StructureGenerator.java:129) [patched_1.17.1.jar:git-Paper-188]
        at net.minecraft.world.level.chunk.storage.ChunkRegionLoader.a(ChunkRegionLoader.java:717) [patched_1.17.1.jar:git-Paper-188]
        at net.minecraft.world.level.chunk.storage.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:272) [patched_1.17.1.jar:git-Paper-188]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:106) [patched_1.17.1.jar:git-Paper-188]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) [patched_1.17.1.jar:git-Paper-188]
        at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) [patched_1.17.1.jar:git-Paper-188]
        at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:49) [patched_1.17.1.jar:git-Paper-188]

**To Reproduce**
1. setup 1.17.1 paper instance (latest as of this bug date)
2. load plugin
3. set worldborder to 25000
4. attempt rtp a few times in a row to see error.

**Expected behavior**
No error should show and it should not crash the server.

**Screenshots**

**Additional context**

**Comment by ScriptJunkieMC** [comment]
Seems to be an issue with 1.17...

https://bugs.mojang.com/si/jira.issueviews:issue-html/MC-227202/MC-227202.html

**Comment by Kubajsa** [comment]
> Seems to be an issue with 1.17...
> 
> https://bugs.mojang.com/si/jira.issueviews:issue-html/MC-227202/MC-227202.html

It is. I'll have to wait for Mojang to fix this.
